// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PdaSeed } from "./PdaSeed";

/**
 * Defines how an account address should be determined
 *Defines how an account address should be determined
 */
export type AccountAddress = { "pubkey": string } | { "pda": { programId: string, seeds: Array<PdaSeed>, } };
