// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedAccount } from "./ParsedAccount";

export type AccountSnapshot = { lamports: bigint, owner: string, executable: boolean, rentEpoch: bigint, 
/**
 * Base64 encoded data
 */
data: string, 
/**
 * Parsed account data if available
 */
parsedData: ParsedAccount | null, };
