// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportSnapshotFilter = { includeProgramAccounts?: boolean, includeAccounts?: Array<string>, excludeAccounts?: Array<string>, 
/**
 * When true, omit accounts owned by the sysvar program.
 */
excludeSysvars?: boolean, 
/**
 * When true, omit accounts whose pubkey is a known agave feature gate
 * (as defined by the `agave_feature_set::FEATURE_NAMES` set built into
 * this surfpool binary). Feature gates added upstream after this version
 * will not be excluded.
 */
excludeFeatureGates?: boolean, };
