// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors [`solana_account_decoder_client_types::ParsedAccount`].
 */
export type ParsedAccount = { program: string, parsed: unknown, space: bigint, };
