// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Seeds used for PDA derivation
 *Seeds used for PDA derivation
 */
export type PdaSeed = { "pubkey": string } | { "string": string } | { "bytes": Array<number> } | { "propertyRef": string } | { "u16Be": number } | { "u16BeRef": string } | { "u16Le": number } | { "bytes32Ref": string } | { "derivedPda": { programId: string, seeds: Array<PdaSeed>, } };
