// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunbookExecutionStatusReport = { startedAt: bigint, completedAt: bigint | null, runbookId: string, errors: Array<string> | null, };
