// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverrideInstance } from "./OverrideInstance";

/**
 * A scenario containing a timeline of overrides
 */
export type Scenario = { 
/**
 * Unique identifier for the scenario (UUID v4 format)
 */
id: string, 
/**
 * Human-readable name
 */
name: string, 
/**
 * Description of this scenario
 */
description: string, 
/**
 * List of override instances in this scenario - MUST be an array, NOT a string
 */
overrides: Array<OverrideInstance>, 
/**
 * Tags for categorization
 */
tags: Array<string>, };
