// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiAccountData } from "./UiAccountData";

/**
 * Mirrors [`solana_account_decoder_client_types::UiAccount`].
 */
export type UiAccount = { lamports: bigint, data: UiAccountData, owner: string, executable: boolean, rentEpoch: bigint, space: bigint | null, };
