// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiAccount } from "./UiAccount";

/**
 * Mirrors [`crate::types::UiAccountChange`], with [`UiAccountDef`] payloads.
 */
export type UiAccountChange = { "type": "create", "data": UiAccount } | { "type": "update", "data": [UiAccount, UiAccount] } | { "type": "delete", "data": UiAccount } | { "type": "unchanged", "data": UiAccount | null };
