// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors [`solana_account_decoder_client_types::UiAccountEncoding`].
 */
export type UiAccountEncoding = "binary" | "base58" | "base64" | "jsonParsed" | "base64+zstd";
