// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedAccount } from "./ParsedAccount";
import type { UiAccountEncoding } from "./UiAccountEncoding";

/**
 * Mirrors [`solana_account_decoder_client_types::UiAccountData`].
 */
export type UiAccountData = string | ParsedAccount | [string, UiAccountEncoding];
