// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiAccount } from "./UiAccount";
import type { UiProfileResult } from "./UiProfileResult";

export type UiKeyedProfileResult = { slot: bigint, key: string, instructionProfiles?: Array<UiProfileResult>, transactionProfile: UiProfileResult, readonlyAccountStates: { [key in string]: UiAccount }, };
