// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiAccountProfileState } from "./UiAccountProfileState";

export type UiProfileResult = { accountStates: { [key in string]: UiAccountProfileState }, computeUnitsConsumed: bigint, logMessages: Array<string> | null, errorMessage: string | null, };
